apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-demo-default
  namespace: mesh-demo
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: ALL_METRICS
      tagOverrides:
        request_id:
          value: request.headers["x-request-id"]
