apiVersion: v1
kind: Service
metadata:
  name: envoy-demo-service
  namespace: demo
  labels:
    app: envoy-demo-app
    demo: gateway-api
spec:
  type: ClusterIP
  selector:
    app: envoy-demo-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
